apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluecapstone
  labels:
    app: bluecapstone
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: bluecapstone
  template:
    metadata:
      labels:
        app: bluecapstone
    spec:
      containers:
        - image: 2002714/bluecapstone:latest
          imagePullPolicy: Always
          name: bluecapstone
          ports:
            - containerPort: 80