apiVersion: apps/v1
kind: Deployment
metadata:
  name: greencapstone
  labels:
    app: greencapstone
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: greencapstone
  template:
    metadata:
      labels:
        app: greencapstone
    spec:
      containers:
        - image: 2002714/greencapstone:latest
          imagePullPolicy: Always
          name: greencapstone
          ports:
            - containerPort: 80